[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "C7TEHSq3mBUoXNiYAeboHor8W3XfJ4SrbkQaoFnTZ5Uc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/longtran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"